export const keywords = {
  cursedSoul: "Cursed Soul",
  nighthaunt: "Nighthaunt",
};

export const units = {
  awlrachTheDrowner: "Awlrach the Drowner",
  cairWraith: "Cairn Wraith",
  guardianOfSouls: "Guardian of Souls",
  knightOfShrouds: "Knight of Shrouds",
  knightOfShroudsOnEtherealSteed: "Knight of Shrouds on Ethereal Steed",
  krulghastCruciator: "Krulghast Cruciator",
  kurdossValentianTheCravenKing: "Kurdoss Valentian, the Craven King",
  ladyOlynderMortarchOfGrief: "Lady Olynder, Mortarch of Grief",
  lordExecutioner: "Lord Executioner",
  nagashSupremeLordOfTheUndead: "Nagash, Supreme Lord of the Undead",
  reikenorTheGrimhailer: "Reikenor the Grimhailer",
  scriptorMortis: "Scriptor Mortis",
  spiritTorment: "Spirit Torment",
  tombBanshee: "Tomb Banshee",
  blackCoach: "Black Coach",
  bladegheistRevenants: "Bladegheist Revenants",
  chainghasts: "Chainghasts",
  chainrasps: "Chainrasps",
  craventhroneGuard: "Craventhrone Guard",
  dreadbladeHarrows: "Dreadblade Harrows",
  dreadscytheHarridans: "Dreadscythe Harridans",
  glaivewraithStalkers: "Glaivewraith Stalkers",
  grimghastReapers: "Grimghast Reapers",
  hexwraiths: "Hexwraiths",
  myrmournBanshees: "Myrmourn Banshees",
  pyregheists: "Pyregheists",
  spiritHosts: "Spirit Hosts",
};
