export const keywords = {
  chaos: "chaos",
  skaven: "skaven",
  masterclan: "masterclan",
  verminus: "verminus",
  skryre: "skryre",
  moulder: "moulder",
  eshin: "eshin",
  pestilens: "pestilens",
  overclaw: "Overclaw",
  daemon: "Daemon",
};

export const units = {
  vizzikSkour: "Vizzik Skour",
  lordSkreechVerminking: "Skreech Verminking",
  thanquol: "Thanquol",
  verminlordCorruptor: "Verminlord Corruptor",
  verminlordWarbringer: "VerminlordWarbringer",
  verminlordDeceiver: "Verminlord Deceiver",
  verminlordWarpseer: "Verminlord Warpseer",
  greySeer: "Grey Seer",
  greySeerOnScreamingBell: "Grey Seer on Screaming Bell",
  archWarlock: "Arch Warlock",
  warlockEngineer: "Warlock Engineer",
  warlockBombardier: "Warlock Bombardier",
  warlockGalvaneer: "Warlock Galvaneer",
  stormFiends: "Stormfiends",
  acolyteGlobadiers: "Acolyte Globadiers",
  warpLightningCannon: "Warp Lightning Cannon",
  warpfireThrowers: "Warpfire Throwers",
  ratlingGuns: "Ratling Guns",
  warpvoltScourgers: "Warpvolt Scourgers",
  warplockJezzails: "Warplock Jezzails",
  ratlingWarpblaster: "Ratling Warpblaster",
  warpGrinder: "Warp Grinder",
  doomFlayer: "Doom Flayers",
  doomwheel: "Doomwheel",
  plagueMonks: "Plague Monks",
  plaguePriestOnPlagueFurnace: "Plague Priest on Plague Furnace",
  plaguePack: "Plague Pack",
  plagueclaw: "Plagueclaw",
  krittokFoulblade: "Krittok Foulblade",
  clawlord: "Clawlord",
  clawlordOnGnawBeast: "Clawlord on Gnaw Beast",
  clanrats: "Clanrats",
  stormvermin: "Stormvermin",
  masterMoulder: "Master Moulder",
  broodTerrror: "Brood Terror",
  ratOgres: "Rat Ogres",
  hellPitAbomination: "Hell Pit Abomination",
  deathmaster: "Deathmaster",
  nightRunners: "Night Runners",
};

export const skavenGeneralKeywords = {
  weaponsTeam: "Weapons team",
};
