export const keywords = {
  deadwalkers: "Deadwalkers",
  deathrattle: "Deathrattle",
  vyrkosRetainer: "Vyrkos Retainer",
  soulblightGravelords: "Soulblight Gravelords",
  deathrattleOverseer: "Deathrattle Overseer",
};

export const units = {
  belladammaVolga: "Belladamma Volga",
  bloodseekerPalanquin: "Bloodseeker Palanquin",
  cadoEzechiar: "Cado Ezechiar",
  covenThrone: "Coven Throne",
  gorslavTheGravekeeper: "Gorslav the Gravekeeper",
  ivyaVolga: "Ivya Volga",
  kritzaTheRatPrince: "Kritza, the Rat Prince",
  ladyAnnika: "Lady Annika",
  laukaVai: "Lauka Vai",
  mannfredVonCarstein: "Mannfred Von Carstein",
  mortisEngine: "Mortis Engine",
  nagashSupremeLordOfTheUndead: "Nagash, Supreme Lord of the Undead",
  necromancer: "Necromancer",
  neferataMortarchOfBlood: "Neferata, Mortarch of Blood",
  princeVhordrai: "Prince Vhordrai",
  radukarTheBeast: "Radukar the Beast",
  radukarTheWolf: "Radukar the Wolf",
  sekharFangOfNulahmia: "Sekhar, Fang of Nulahmia",
  torgilliusTheChamberlain: "Torgillius the Chamberlain",
  vampireLord: "Vampire Lord",
  vampireLordOnZombieDragon: "Vampire Lord on Zombie Dragon",
  vengorianLord: "Vengorian Lord",
  watchCaptainHalgrim: "Watch Captain Halgrim",
  wightKing: "Wight King",
  wightKingOnSkeletalSteed: "Wight King on Skeletal Steed",
  askurganTrueblades: "Askurgan Trueblades",
  blackKnights: "Black Knights",
  bloodKnights: "Blood Knights",
  corpseCart: "Corpse Cart",
  deadwalkerZombies: "Deadwalker Zombies",
  deathrattleSkeletons: "Deathrattle Skeletons",
  direwolves: "Dire Wolves",
  fellBats: "Fell Bats",
  graveGuard: "Grave Guard",
  kosargiNightguard: "Kosargi Nightguard",
  terrorGheist: "Terrorgheist",
  vargheists: "Vargheists",
  vargskyr: "Vargskyr",
  vyrkosBloodBorn: "Vyrkos Blood-born",
  zombieDragon: "Zombie Dragon",
};
