import { Hero, Unit, UnitTypes } from "@/types";
import {
  keywords,
  skavenKeywords,
  skavenUnits,
  skavenGeneralKeywords,
} from "../constants";

const {
  chaos,
  skaven,
  masterclan,
  verminus,
  skryre,
  overclaw,
  pestilens,
  eshin,
  moulder,
  daemon,
} = skavenKeywords;
const {
  hero,
  wizard,
  infantry,
  warMachine,
  monster,
  cavalry,
  priest,
  unique,
  ward,
  warmaster,
} = keywords;
const { weaponsTeam } = skavenGeneralKeywords;

export const battleFormations = [
  "Warpcog Convocation",
  "Claw Horde",
  "Fleshmeld Managerie",
  "Virilunt Procession",
];

export const artifactsOfPower = ["Foulhide", "Warpstone Charm", "Skavenbrew"];

export const heroicTraits = [
  "Scurry Away",
  "Short Tempered",
  "Skill Manipulator",
];

export const spellLores = ["Lore of Ruin"];

export const prayerLores = ["Noxious Prayers"];

export const manifestationLore = ["Manifestations of Doom"];

const subordinateRules = {
  oneWeaponTeam: { keyword: weaponsTeam, max: 1 },
  oneWarmachine: { keyword: warMachine, max: 1 },
  oneOverclaw: { keyword: overclaw, max: 1, hero: true },
  oneUnitOfClanrats: { keyword: skavenUnits.clanrats, max: 1 },
  anySkaven: [
    { keyword: skaven, max: 0 },
    { keyword: weaponsTeam, max: 1 },
    { keyword: warMachine, max: 1 },
  ],
};

export const skavenHeroProfiles: Hero[] = [
  {
    id: "1",
    name: skavenUnits.archWarlock,
    cost: 175,
    quantity: 1,
    subordinates: [
      { keyword: skryre, max: 0 },
      subordinateRules.oneUnitOfClanrats,
    ],
    keywords: [hero, wizard[1], infantry],
    factionKeywords: [chaos, skaven, skaven],
  },
  {
    id: "2",
    name: skavenUnits.clawlord,
    cost: 80,
    quantity: 1,
    keywords: [hero, infantry, skavenUnits.clawlord],
    subordinates: [{ keyword: verminus, max: 0 }],
    factionKeywords: [chaos, skaven, verminus, overclaw, skavenUnits.clawlord],
  },
  {
    id: "3",
    name: skavenUnits.clawlordOnGnawBeast,
    cost: 130,
    quantity: 1,
    subordinates: [{ keyword: verminus, max: 0 }],
    keywords: [hero, cavalry],
    factionKeywords: [chaos, skaven, verminus, overclaw, skavenUnits.clawlord],
  },
  {
    id: "4",
    name: skavenUnits.deathmaster,
    cost: 120,
    quantity: 1,
    subordinates: [
      { keyword: eshin, max: 0 },
      subordinateRules.oneUnitOfClanrats,
    ],
    keywords: [hero, infantry],
    factionKeywords: [
      chaos,
      skaven,
      masterclan,
      overclaw,
      skavenUnits.deathmaster,
    ],
  },
  {
    id: "5",
    name: skavenUnits.greySeer,
    cost: 120,
    quantity: 1,
    subordinates: [subordinateRules.oneOverclaw, ...subordinateRules.anySkaven],
    keywords: [hero, wizard[1], infantry],
    factionKeywords: [chaos, skaven, masterclan],
  },
  {
    id: "6",
    name: skavenUnits.greySeerOnScreamingBell,
    cost: 350,
    quantity: 1,
    subordinates: [subordinateRules.oneOverclaw, ...subordinateRules.anySkaven],
    keywords: [hero, wizard[2], warMachine, ward.fivePlus],
    factionKeywords: [chaos, skaven, masterclan],
  },
  {
    id: "7",
    name: skavenUnits.krittokFoulblade,
    cost: 180,
    quantity: 1,
    subordinates: [{ keyword: verminus, max: 0 }],
    keywords: [hero, unique, infantry, warmaster],
    factionKeywords: [chaos, skaven, verminus],
  },
  {
    id: "8",
    name: skavenUnits.lordSkreechVerminking,
    cost: 410,
    quantity: 1,
    subordinates: [subordinateRules.oneOverclaw, { keyword: skaven, max: 0 }],
    keywords: [monster, hero, unique, wizard[1], ward.fivePlus, warmaster],
    factionKeywords: [
      chaos,
      skaven,
      masterclan,
      verminus,
      pestilens,
      eshin,
      skryre,
      moulder,
    ],
  },
  {
    id: "9",
    name: skavenUnits.masterMoulder,
    cost: 100,
    quantity: 1,
    subordinates: [
      subordinateRules.oneUnitOfClanrats,
      { keyword: moulder, max: 0 },
    ],
    keywords: [hero, infantry],
    factionKeywords: [chaos, skaven, moulder],
  },
  {
    id: "10",
    name: skavenUnits.plaguePriestOnPlagueFurnace,
    cost: 340,
    quantity: 1,
    subordinates: [
      subordinateRules.oneUnitOfClanrats,
      { keyword: pestilens, max: 0 },
    ],
    keywords: [hero, priest[1], warMachine, ward.fivePlus],
    factionKeywords: [chaos, skaven, pestilens],
  },
  {
    id: "11",
    name: skavenUnits.thanquol,
    cost: 360,
    quantity: 1,
    subordinates: [subordinateRules.oneOverclaw, ...subordinateRules.anySkaven],
    keywords: [hero, monster, wizard[2], ward.fivePlus, warmaster, unique],
    factionKeywords: [chaos, skaven, masterclan],
  },
  {
    id: "12",
    name: skavenUnits.verminlordCorruptor,
    cost: 330,
    quantity: 1,
    subordinates: [
      subordinateRules.oneUnitOfClanrats,
      { keyword: pestilens, max: 0 },
    ],
    keywords: [monster, hero, wizard[1], ward.fivePlus],
    factionKeywords: [chaos, skaven, daemon, pestilens],
  },
  {
    id: "13",
    name: skavenUnits.verminlordDeceiver,
    cost: 410,
    quantity: 1,
    subordinates: [
      subordinateRules.oneUnitOfClanrats,
      { keyword: skavenUnits.deathmaster, max: 1, hero: true },
      { keyword: eshin, max: 0 },
    ],
    keywords: [monster, hero, wizard[1], ward.fivePlus],
    factionKeywords: [chaos, skaven, daemon, eshin],
  },
  {
    id: "14",
    name: skavenUnits.verminlordWarbringer,
    cost: 320,
    quantity: 1,
    subordinates: [
      { keyword: skavenUnits.clawlord, max: 1 },
      { keyword: verminus, max: 0 },
    ],
    keywords: [monster, hero, wizard[1], ward.fivePlus],
    factionKeywords: [chaos, skaven, daemon, verminus],
  },
  {
    id: "15",
    name: skavenUnits.verminlordWarpseer,
    cost: 340,
    quantity: 1,
    subordinates: [
      { keyword: skavenUnits.clawlord, max: 1, hero: true },
      ...subordinateRules.anySkaven,
    ],
    keywords: [monster, hero, wizard[1], ward.fivePlus],
    factionKeywords: [chaos, skaven, daemon, masterclan],
  },
  {
    id: "16",
    name: skavenUnits.vizzikSkour,
    cost: 400,
    quantity: 1,
    subordinates: [subordinateRules.oneOverclaw, ...subordinateRules.anySkaven],
    keywords: [hero, unique, monster, priest[2], ward.fivePlus, warmaster],
    factionKeywords: [chaos, skaven, daemon, masterclan],
  },
  {
    id: "17",
    name: skavenUnits.warlockBombardier,
    cost: 110,
    quantity: 1,
    subordinates: [
      subordinateRules.oneUnitOfClanrats,
      { keyword: skryre, max: 0 },
    ],
    keywords: [hero, infantry],
    factionKeywords: [chaos, skaven, skryre, overclaw],
  },
  {
    id: "18",
    name: skavenUnits.warlockEngineer,
    cost: 130,
    quantity: 1,
    subordinates: [
      { keyword: skryre, max: 0 },
      subordinateRules.oneUnitOfClanrats,
    ],
    keywords: [hero, infantry],
    factionKeywords: [chaos, skaven, skryre, overclaw],
  },
  {
    id: "19",
    name: skavenUnits.warlockGalvaneer,
    cost: 130,
    quantity: 1,
    subordinates: [
      subordinateRules.oneUnitOfClanrats,
      { keyword: skryre, max: 0 },
    ],
    keywords: [hero, infantry],
    factionKeywords: [chaos, skaven, skryre, overclaw],
  },
];

export const skavenUnitProfiles: Unit[] = [
  {
    id: "20",
    name: skavenUnits.acolyteGlobadiers,
    cost: 100,
    quantity: 5,
    keywords: [infantry],
    factionKeywords: [chaos, skaven, skryre],
  },
  {
    id: "21",
    name: skavenUnits.broodTerrror,
    cost: 260,
    quantity: 1,
    keywords: [monster],
    factionKeywords: [chaos, skaven, moulder],
  },
  {
    id: "22",
    name: skavenUnits.clanrats,
    cost: 150,
    quantity: 20,
    keywords: [infantry],
    factionKeywords: [chaos, skaven, verminus, skavenUnits.clanrats],
  },
  {
    id: "23",
    name: skavenUnits.doomFlayer,
    cost: 130,
    quantity: 2,
    keywords: [warMachine],
    factionKeywords: [chaos, skaven, skryre, warMachine],
  },
  {
    id: "24",
    name: skavenUnits.doomwheel,
    cost: 120,
    quantity: 1,
    keywords: [warMachine],
    factionKeywords: [chaos, skaven, skryre, warMachine],
  },
  {
    id: "25",
    name: skavenUnits.hellPitAbomination,
    cost: 240,
    quantity: 1,
    keywords: [monster],
    factionKeywords: [chaos, skaven, moulder],
  },
  {
    id: "26",
    name: skavenUnits.nightRunners,
    cost: 130,
    quantity: 10,
    keywords: [infantry],
    factionKeywords: [chaos, skaven, eshin],
  },
  {
    id: "27",
    name: skavenUnits.plagueMonks,
    cost: 140,
    quantity: 20,
    keywords: [infantry],
    factionKeywords: [chaos, skaven, pestilens],
  },
  {
    id: "28",
    name: skavenUnits.plaguePack,
    cost: 120,
    quantity: 5,
    keywords: [infantry],
    factionKeywords: [chaos, skaven, pestilens],
  },
  {
    id: "29",
    name: skavenUnits.plagueclaw,
    cost: 140,
    quantity: 1,
    keywords: [warMachine],
    factionKeywords: [chaos, skaven, pestilens],
  },
  {
    id: "30",
    name: skavenUnits.ratOgres,
    cost: 160,
    quantity: 3,
    keywords: [infantry],
    factionKeywords: [chaos, skaven, moulder],
  },
  {
    id: "31",
    name: skavenUnits.ratlingGuns,
    cost: 170,
    quantity: 3,
    keywords: [infantry, weaponsTeam],
    factionKeywords: [chaos, skaven, skryre, weaponsTeam],
  },
  {
    id: "32",
    name: skavenUnits.ratlingWarpblaster,
    cost: 150,
    quantity: 1,
    keywords: [warMachine],
    factionKeywords: [chaos, skaven, skryre, warMachine],
  },
  {
    id: "33",
    name: skavenUnits.stormFiends,
    cost: 260,
    quantity: 3,
    keywords: [infantry],
    factionKeywords: [chaos, skaven, skryre, moulder],
  },
  {
    id: "34",
    name: skavenUnits.stormvermin,
    cost: 120,
    quantity: 10,
    keywords: [infantry],
    factionKeywords: [chaos, skaven, verminus],
  },
  {
    id: "35",
    name: skavenUnits.warpGrinder,
    cost: 140,
    quantity: 1,
    keywords: [warMachine],
    factionKeywords: [chaos, skaven, skryre, warMachine],
  },
  {
    id: "36",
    name: skavenUnits.warpLightningCannon,
    cost: 140,
    quantity: 1,
    keywords: [warMachine],
    factionKeywords: [chaos, skaven, skryre, warMachine],
  },
  {
    id: "37",
    name: skavenUnits.warpfireThrowers,
    cost: 140,
    quantity: 3,
    keywords: [infantry, weaponsTeam],
    factionKeywords: [chaos, skaven, skryre, weaponsTeam],
  },
  {
    id: "38",
    name: skavenUnits.warplockJezzails,
    cost: 150,
    quantity: 3,
    keywords: [infantry],
    factionKeywords: [chaos, skaven, skryre],
  },
  {
    id: "39",
    name: skavenUnits.warpvoltScourgers,
    cost: 190,
    quantity: 3,
    keywords: [infantry, weaponsTeam],
    factionKeywords: [chaos, skaven, skryre, weaponsTeam],
  },
];

export const skavenBattleProfiles: UnitTypes[] = [
  ...skavenHeroProfiles,
  ...skavenUnitProfiles,
];
