import { Hero, Unit, UnitTypes } from "@/types";
import {
  soulblightGravelordKeywords,
  soulblightUnits,
  keywords,
} from "@/constants";

const {
  deadwalkers,
  deathrattle,
  vyrkosRetainer,
  soulblightGravelords,
  deathrattleOverseer,
} = soulblightGravelordKeywords;
const { hero, unique } = keywords;

const takeDeathrattleOverseer = {
  keyword: deathrattleOverseer,
  max: 1,
  hero: true,
};

export const soulblightHeroProfiles: Hero[] = [
  {
    name: soulblightUnits.belladammaVolga,
    id: "1",
    cost: 220,
    quantity: 1,
    keywords: [hero, unique],
    factionKeywords: [],
    subordinates: [
      { keyword: soulblightGravelords, max: 0 },
      { keyword: vyrkosRetainer, max: 1, hero: true },
    ],
  },
  {
    name: soulblightUnits.bloodseekerPalanquin,
    id: "2",
    cost: 230,
    quantity: 1,
    keywords: [hero],
    factionKeywords: [],
    subordinates: [{ keyword: soulblightGravelords, max: 0 }],
  },
  {
    name: soulblightUnits.cadoEzechiar,
    id: "3",
    cost: 150,
    quantity: 1,
    keywords: [hero, unique],
    factionKeywords: [],
    subordinates: [{ keyword: soulblightGravelords, max: 0 }],
  },
  {
    name: soulblightUnits.covenThrone,
    id: "4",
    cost: 250,
    quantity: 1,
    keywords: [hero],
    factionKeywords: [],
    subordinates: [{ keyword: soulblightGravelords, max: 0 }],
  },
  {
    name: soulblightUnits.gorslavTheGravekeeper,
    id: "5",
    cost: 120,
    quantity: 1,
    keywords: [hero, unique],
    factionKeywords: [vyrkosRetainer],
    subordinates: [{ keyword: deadwalkers, max: 0 }],
  },
  {
    name: soulblightUnits.ivyaVolga,
    id: "6",
    cost: 120,
    quantity: 1,
    keywords: [hero, unique],
    factionKeywords: [vyrkosRetainer],
    subordinates: [{ keyword: soulblightGravelords, max: 0 }],
  },
  {
    name: soulblightUnits.kritzaTheRatPrince,
    id: "7",
    cost: 70,
    quantity: 1,
    keywords: [hero, unique],
    factionKeywords: [vyrkosRetainer],
    subordinates: [{ keyword: soulblightGravelords, max: 0 }],
  },
  {
    name: soulblightUnits.ladyAnnika,
    id: "8",
    cost: 130,
    quantity: 1,
    keywords: [hero, unique],
    factionKeywords: [vyrkosRetainer],
    subordinates: [{ keyword: soulblightGravelords, max: 0 }],
  },
  {
    name: soulblightUnits.laukaVai,
    id: "9",
    cost: 270,
    quantity: 1,
    keywords: [hero, unique],
    factionKeywords: [],
    subordinates: [
      { keyword: soulblightGravelords, max: 0 },
      takeDeathrattleOverseer,
    ],
  },
  {
    name: soulblightUnits.mannfredVonCarstein,
    id: "10",
    cost: 430,
    quantity: 1,
    keywords: [hero, unique],
    factionKeywords: [],
    subordinates: [
      { keyword: soulblightGravelords, max: 0 },
      takeDeathrattleOverseer,
    ],
  },
  {
    name: soulblightUnits.mortisEngine,
    id: "11",
    cost: 240,
    quantity: 1,
    keywords: [hero],
    factionKeywords: [],
    subordinates: [{ keyword: deadwalkers, max: 0 }],
  },
  {
    name: soulblightUnits.nagashSupremeLordOfTheUndead,
    id: "12",
    cost: 880,
    quantity: 1,
    keywords: [hero, unique],
    factionKeywords: [],
    subordinates: [
      { keyword: soulblightGravelords, max: 0 },
      takeDeathrattleOverseer,
    ],
  },
  {
    name: soulblightUnits.necromancer,
    id: "13",
    cost: 140,
    quantity: 1,
    keywords: [hero],
    factionKeywords: [],
    subordinates: [{ keyword: soulblightGravelords, max: 0 }],
  },
  {
    name: soulblightUnits.neferataMortarchOfBlood,
    id: "14",
    cost: 460,
    quantity: 1,
    keywords: [hero, unique],
    factionKeywords: [],
    subordinates: [
      { keyword: soulblightGravelords, max: 0 },
      takeDeathrattleOverseer,
    ],
  },
  {
    name: soulblightUnits.princeVhordrai,
    id: "15",
    cost: 480,
    quantity: 1,
    keywords: [hero, unique],
    factionKeywords: [],
    subordinates: [
      { keyword: soulblightGravelords, max: 0 },
      takeDeathrattleOverseer,
    ],
  },
  {
    name: soulblightUnits.radukarTheBeast,
    id: "16",
    cost: 300,
    quantity: 1,
    keywords: [hero, unique],
    factionKeywords: [],
    subordinates: [
      { keyword: soulblightGravelords, max: 0 },
      { keyword: vyrkosRetainer, max: 1, hero: true },
    ],
  },
  {
    name: soulblightUnits.radukarTheWolf,
    id: "17",
    cost: 150,
    quantity: 1,
    keywords: [hero, unique],
    factionKeywords: [],
    subordinates: [
      { keyword: soulblightGravelords, max: 0 },
      { keyword: vyrkosRetainer, max: 1, hero: true },
    ],
  },
  {
    name: soulblightUnits.sekharFangOfNulahmia,
    id: "18",
    cost: 210,
    quantity: 1,
    keywords: [hero, unique],
    factionKeywords: [],
    subordinates: [{ keyword: soulblightGravelords, max: 0 }],
  },
  {
    name: soulblightUnits.torgilliusTheChamberlain,
    id: "19",
    cost: 180,
    quantity: 1,
    keywords: [hero, unique],
    factionKeywords: [vyrkosRetainer],
    subordinates: [{ keyword: soulblightGravelords, max: 0 }],
  },
  {
    name: soulblightUnits.vampireLord,
    id: "20",
    cost: 160,
    quantity: 1,
    keywords: [hero],
    factionKeywords: [],
    subordinates: [{ keyword: soulblightGravelords, max: 0 }],
  },
  {
    name: soulblightUnits.vampireLordOnZombieDragon,
    id: "21",
    cost: 400,
    quantity: 1,
    keywords: [hero],
    factionKeywords: [],
    subordinates: [{ keyword: soulblightGravelords, max: 0 }],
  },
  {
    name: soulblightUnits.vengorianLord,
    id: "22",
    cost: 250,
    quantity: 1,
    keywords: [hero],
    factionKeywords: [],
    subordinates: [{ keyword: soulblightGravelords, max: 0 }],
  },
  {
    name: soulblightUnits.watchCaptainHalgrim,
    id: "23",
    cost: 110,
    quantity: 1,
    keywords: [hero, unique],
    factionKeywords: [vyrkosRetainer],
    subordinates: [{ keyword: deathrattle, max: 0 }],
  },
  {
    name: soulblightUnits.wightKing,
    id: "24",
    cost: 100,
    quantity: 1,
    keywords: [hero],
    factionKeywords: [deathrattleOverseer],
    subordinates: [{ keyword: deathrattle, max: 0 }],
  },
  {
    name: soulblightUnits.wightKingOnSkeletalSteed,
    id: "25",
    cost: 140,
    quantity: 1,
    keywords: [hero],
    factionKeywords: [deathrattleOverseer],
    subordinates: [{ keyword: deathrattle, max: 0 }],
  },
];

const soulblightUnitsProfiles: Unit[] = [
  {
    name: soulblightUnits.askurganTrueblades,
    id: "26",
    cost: 130,
    quantity: 8,
    keywords: [],
    factionKeywords: [soulblightGravelords],
    cannotBeReinforced: true,
  },
  {
    name: soulblightUnits.blackKnights,
    id: "27",
    cost: 180,
    quantity: 5,
    keywords: [],
    factionKeywords: [deathrattle, soulblightGravelords],
  },
  {
    name: soulblightUnits.bloodKnights,
    id: "28",
    cost: 230,
    quantity: 5,
    keywords: [],
    factionKeywords: [soulblightGravelords],
  },
  {
    name: soulblightUnits.corpseCart,
    id: "29",
    cost: 70,
    quantity: 1,
    keywords: [],
    factionKeywords: [deadwalkers, soulblightGravelords],
  },
  {
    name: soulblightUnits.deadwalkerZombies,
    id: "30",
    cost: 150,
    quantity: 20,
    keywords: [],
    factionKeywords: [deadwalkers, soulblightGravelords],
  },
  {
    name: soulblightUnits.deathrattleSkeletons,
    id: "31",
    cost: 100,
    quantity: 10,
    keywords: [],
    factionKeywords: [deathrattle, soulblightGravelords],
  },
  {
    name: soulblightUnits.direwolves,
    id: "32",
    cost: 140,
    quantity: 5,
    keywords: [],
    factionKeywords: [deadwalkers, soulblightGravelords],
  },
  {
    name: soulblightUnits.fellBats,
    id: "33",
    cost: 100,
    quantity: 3,
    keywords: [],
    factionKeywords: [deadwalkers, soulblightGravelords],
  },
  {
    name: soulblightUnits.graveGuard,
    id: "34",
    cost: 160,
    quantity: 10,
    keywords: [],
    factionKeywords: [deathrattle, soulblightGravelords],
  },
  {
    name: soulblightUnits.kosargiNightguard,
    id: "35",
    cost: 120,
    quantity: 5,
    keywords: [],
    factionKeywords: [deadwalkers, soulblightGravelords],
  },
  {
    name: soulblightUnits.terrorGheist,
    id: "36",
    cost: 240,
    quantity: 1,
    keywords: [],
    factionKeywords: [soulblightGravelords],
  },
  {
    name: soulblightUnits.vargheists,
    id: "37",
    cost: 130,
    quantity: 3,
    keywords: [],
    factionKeywords: [soulblightGravelords],
  },
  {
    name: soulblightUnits.vargskyr,
    id: "38",
    cost: 160,
    quantity: 1,
    keywords: [],
    factionKeywords: [soulblightGravelords],
  },
  {
    name: soulblightUnits.vyrkosBloodBorn,
    id: "39",
    cost: 150,
    quantity: 5,
    keywords: [],
    factionKeywords: [soulblightGravelords],
    cannotBeReinforced: true,
  },
  {
    name: soulblightUnits.zombieDragon,
    id: "40",
    cost: 250,
    quantity: 1,
    keywords: [],
    factionKeywords: [soulblightGravelords],
  },
];

export const soulblightBattleProfiles: UnitTypes[] = [
  ...soulblightHeroProfiles,
  ...soulblightUnitsProfiles,
];

export const battleFormations = [
  "Legion of Shyish",
  "Bacchanal of Blood",
  "Deathstench Drove",
  "Deathmarch",
];

export const artifactsOfPower = [
  "Orb of Enchantment",
  "Shard of Night",
  "Amulet of Screams",
];

export const heroicTraits = [
  "Lash of the Sire",
  "Unbending Will",
  "Unhinged Rampager",
];

export const spellLores = ["Lore of Undeath"];

export const prayerLores = [];

export const manifestationLore = [];
